const K='sut_rfid_db_v5';
const seed={
 users:[
  {id:1,name:'ผู้ดูแลระบบ',username:'admin',password:'admin123',role:'admin',active:true},
  {id:2,name:'ดิเรกฤทธิ์ แสงโชติ',username:'direkrit',password:'1234',role:'user',active:true}
 ],
 assets:[
  {id:'7440-001-0001/2563',name:'เครื่องคอมพิวเตอร์',brand:'Acer Aspire 5',epc:'300BB3A4F2C1E8D0',status:'ใช้งานปกติ',room:'ห้องปฏิบัติการคอมพิวเตอร์',user:'ดิเรกฤทธิ์ แสงโชติ',image:''},
  {id:'7440-001-0002/2563',name:'เครื่องปั่นเหวี่ยง',brand:'Eppendorf',epc:'300BB3A4F2C1E8D1',status:'ส่งซ่อม',room:'ห้องปฏิบัติการ',user:'',image:''},
  {id:'7440-001-0003/2563',name:'ตู้เย็นเก็บตัวอย่าง',brand:'Sanyo',epc:'300BB3A4F2C1E8D2',status:'ถึงรอบบำรุงรักษา',room:'ห้องเก็บตัวอย่าง',user:'',image:''}
 ],
 maintenance:[{id:1,asset:'7440-001-0002/2563',due:'2026-10-12',cycle:'180 วัน',status:'ใกล้ครบกำหนด',lastDate:'2026-04-15',note:'ตรวจสภาพและทำความสะอาด'}],
 repairs:[],usage:[]
};
let db=JSON.parse(localStorage.getItem(K)||'null')||JSON.parse(localStorage.getItem('sut_rfid_db_v4')||'null')||JSON.parse(localStorage.getItem('sut_rfid_db_v3')||'null')||structuredClone(seed);
db.users??=[];db.assets??=[];db.maintenance??=[];db.repairs??=[];db.usage??=[];db.assets.forEach(a=>a.image??='');
let me=null,page='home',serialPort=null,serialReader=null,scanRunning=false,scanSeen=new Set(),csvTarget='assets';
try{me=db.users.find(u=>u.username===localStorage.getItem('sut_user')&&u.active)||null}catch(e){}
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const save=()=>localStorage.setItem(K,JSON.stringify(db));
const go=p=>{page=p;render()};
const v=id=>document.getElementById(id)?.value??'';
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>Date.now()+Math.floor(Math.random()*1000);
function login(){const u=db.users.find(x=>x.username===v('lu')&&x.password===v('lp')&&x.active);if(!u)return alert('ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง');me=u;localStorage.setItem('sut_user',u.username);render()}
function logout(){me=null;localStorage.removeItem('sut_user');stopScan(true);render()}
function render(){document.getElementById('app').innerHTML=me?shell():loginPage()}
function loginPage(){return `<div class="login"><div class="loginbox"><img src="sut-logo.jpg"><h2>ระบบจัดการครุภัณฑ์ RFID</h2><div class="orange">ศูนย์เครื่องมือวิทยาศาสตร์และเทคโนโลยี</div><div class="field"><label>ชื่อผู้ใช้งาน</label><input id="lu" autocomplete="username"></div><div class="field"><label>รหัสผ่าน</label><input id="lp" type="password" autocomplete="current-password" onkeydown="if(event.key==='Enter')login()"></div><button class="btn" onclick="login()">เข้าสู่ระบบ</button><p style="font-size:12px;color:#8998a8">บัญชีเริ่มต้น: admin / admin123</p></div></div>`}
function shell(){let nav=[['home','หน้าหลัก'],['scan','ตรวจนับ RFID'],['assets','จัดการครุภัณฑ์'],['maintenance','Maintenance'],['usage','ประวัติการใช้งาน'],['repairs','การแจ้งซ่อม / ซ่อมบำรุง'],['reports','นำเข้า / ส่งออก CSV']];if(me.role==='admin')nav.push(['users','จัดการผู้ใช้งาน']);nav.push(['settings','ตั้งค่า']);return `<div class="layout"><aside class="side"><div class="brand"><img src="sut-logo.jpg"><div><b>ศูนย์เครื่องมือวิทยาศาสตร์และเทคโนโลยี</b><small>มหาวิทยาลัยเทคโนโลยีสุรนารี</small></div></div><div class="nav">${nav.map(n=>`<button class="${page===n[0]?'active':''}" onclick="go('${n[0]}')">${n[1]}</button>`).join('')}</div></aside><main class="main"><header class="top"><b>${title()}</b><div>👤 ${esc(me.name)} <span class="badge info">${esc(me.role)}</span> <button class="btn gray" onclick="logout()">ออกจากระบบ</button></div></header><section class="content">${body()}</section></main></div><div id="modal" class="modal"></div>`}
function title(){return {home:'หน้าหลัก',scan:'ตรวจนับ RFID',assets:'จัดการครุภัณฑ์',maintenance:'Maintenance / รอบบำรุงรักษา',usage:'ประวัติการใช้งาน',repairs:'การแจ้งซ่อม / ซ่อมบำรุง',reports:'นำเข้า / ส่งออก CSV',users:'จัดการผู้ใช้งาน',settings:'ตั้งค่า'}[page]||'หน้าหลัก'}
function counts(){let a=db.assets;return [a.length,a.filter(x=>x.status==='ใช้งานปกติ').length,a.filter(x=>x.status==='ส่งซ่อม').length,a.filter(x=>x.status==='ถึงรอบบำรุงรักษา').length,db.users.filter(x=>x.active).length]}
function body(){if(page==='home')return home();if(page==='scan')return scan();if(page==='assets')return assets();if(page==='maintenance')return maintenance();if(page==='usage')return usage();if(page==='repairs')return repairs();if(page==='reports')return reports();if(page==='users'&&me.role==='admin')return users();return settings()}
function home(){let[t,o,r,d,u]=counts();let overdue=db.maintenance.filter(m=>m.due&&m.due<today()).length;return `<div class="hero"><div class="heroLeft"><img src="sut-logo.jpg"><div><h1>ศูนย์เครื่องมือวิทยาศาสตร์และเทคโนโลยี</h1><div class="orange">มหาวิทยาลัยเทคโนโลยีสุรนารี</div></div></div><div><h2>ระบบบริหารจัดการครุภัณฑ์ RFID</h2><div style="color:#718096">ตรวจนับ • ติดตาม • ใช้งาน • ซ่อมบำรุง • นำเข้า/ส่งออก CSV</div></div></div><div class="cards"><div class="stat s1">ครุภัณฑ์ทั้งหมด<b>${t}</b>รายการ</div><div class="stat s2">ใช้งานปกติ<b>${o}</b>รายการ</div><div class="stat s3">ส่งซ่อม<b>${r}</b>รายการ</div><div class="stat s4">ถึงรอบบำรุงรักษา<b>${d}</b>รายการ</div><div class="stat s5">ผู้ใช้งาน<b>${u}</b>คน</div></div><div class="grid"><div class="card"><h3>สถานะครุภัณฑ์</h3>${['ใช้งานปกติ','ส่งซ่อม','ถึงรอบบำรุงรักษา'].map((s,i)=>{let n=[o,r,d][i],p=t?Math.round(n/t*100):0;return `<p>${s}<b style="float:right">${n} (${p}%)</b></p><div style="height:9px;background:#edf1f5;border-radius:9px"><div style="width:${p}%;height:100%;background:${['#13a66a','#f28c18','#e94b4b'][i]};border-radius:9px"></div></div>`}).join('')}</div><div class="card"><h3>การแจ้งเตือน</h3><p>รายการใกล้ครบกำหนด <b style="float:right">${db.maintenance.filter(m=>m.status==='ใกล้ครบกำหนด').length}</b></p><p>เกินกำหนด <b style="float:right;color:#e94b4b">${overdue}</b></p><p>กำลังซ่อม <b style="float:right">${db.repairs.filter(r=>r.status!=='ซ่อมเสร็จ').length}</b></p></div></div><div class="grid"><div class="card"><h3>ครุภัณฑ์ล่าสุด</h3>${tableAssets(db.assets.slice(-5).reverse())}</div><div class="card"><h3>บำรุงรักษารอบถัดไป</h3>${maintTable()}</div></div>`}
function name(id){return db.assets.find(a=>a.id===id)?.name||id}
function cls(s){return s==='ใช้งานปกติ'?'ok':s==='ส่งซ่อม'?'repair':s==='ถึงรอบบำรุงรักษา'?'danger':'info'}
function tableAssets(a){return `<table><tr><th>ครุภัณฑ์</th><th>EPC</th><th>ห้อง/สถานที่</th><th>สถานะ</th><th></th></tr>${a.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.epc)}</td><td>${esc(x.room)}</td><td><span class="badge ${cls(x.status)}">${esc(x.status)}</span></td><td><button class="btn gray" onclick="assetForm('${esc(x.id)}')">ดู/แก้ไข</button></td></tr>`).join('')}</table>`}
function assets(){return `<div class="toolbar"><button class="btn" onclick="assetForm()">+ เพิ่มครุภัณฑ์</button><button class="btn orange" onclick="go('reports')">นำเข้า/ส่งออก CSV</button></div><div class="card"><input id="assetSearch" placeholder="ค้นหาเลขครุภัณฑ์ / ชื่อ / EPC / ห้อง" oninput="filterAssets()" style="width:100%;padding:10px;border:1px solid var(--line);border-radius:8px;margin-bottom:12px">${tableAssets(db.assets)}</div>`}
function filterAssets(){let q=v('assetSearch').toLowerCase();let rows=db.assets.filter(a=>JSON.stringify(a).toLowerCase().includes(q));document.querySelector('.card table')?.replaceWith(new DOMParser().parseFromString(tableAssets(rows),'text/html').body.firstChild)}
function scan(){let found=[...scanSeen].map(epc=>db.assets.find(a=>String(a.epc).toUpperCase()===String(epc).toUpperCase())).filter(Boolean);return `<div class="grid"><div class="card"><h3>ตรวจนับ RFID / ESP32</h3><p>เชื่อมต่อ ESP32 ผ่าน USB ด้วย Web Serial (Chrome/Edge) โดยให้ ESP32 ส่ง EPC 1 รายการต่อ 1 บรรทัดที่ 115200 baud</p><div class="toolbar"><button class="btn" onclick="connectESP32()">🔌 เชื่อมต่อ ESP32</button><button class="btn orange" onclick="startDemoScan()">เริ่มสแกนจำลอง</button><button class="btn gray" onclick="stopScan()">หยุด</button><button class="btn gray" onclick="clearScan()">ล้างผล</button></div><div class="notice">${scanRunning?'🟢 กำลังรับข้อมูลจาก ESP32':'⚪ ยังไม่ได้สแกน'}</div><p>พบ EPC <b>${scanSeen.size}</b> | ตรงกับฐานข้อมูล <b>${found.length}</b> / ${db.assets.length}</p></div><div class="card"><h3>ผลการตรวจนับ</h3>${found.length?tableAssets(found):'<div class="empty">ยังไม่พบ EPC ที่ตรงกับฐานข้อมูล</div>'}</div></div>`}
async function connectESP32(){
  if(typeof connectESP32BLE==='function') return connectESP32BLE();
  alert('ระบบ Bluetooth ยังโหลดไม่เสร็จ กรุณารีเฟรชหน้าเว็บ');
}
async function readSerial(){while(scanRunning&&serialReader){try{const {value,done}=await serialReader.read();if(done)break;if(value)value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).forEach(recordEPC)}catch(e){break}}}
function recordEPC(epc){epc=String(epc).trim().replace(/^EPC[:=\s]*/i,'');if(!epc)return;scanSeen.add(epc.toUpperCase());let a=db.assets.find(x=>String(x.epc).toUpperCase()===epc.toUpperCase());if(a){db.usage.unshift({id:uid(),time:new Date().toLocaleString('th-TH'),user:me.name,asset:a.id,action:'ตรวจพบ RFID'});save()}if(page==='scan')render()}
async function stopScan(silent=false){scanRunning=false;try{if(serialReader){await serialReader.cancel();serialReader=null}if(serialPort){await serialPort.close();serialPort=null}}catch(e){}if(!silent&&page==='scan')render()}
function clearScan(){scanSeen=new Set();render()}
function startDemoScan(){scanRunning=true;scanSeen=new Set(db.assets.map(a=>a.epc).filter(Boolean));db.assets.forEach(a=>db.usage.unshift({id:uid(),time:new Date().toLocaleString('th-TH'),user:me.name,asset:a.id,action:'ตรวจพบ RFID (จำลอง)'}));save();render()}
function maintenance(){let overdue=db.maintenance.filter(m=>m.due&&m.due<today()).length;return `<div class="toolbar"><button class="btn" onclick="maintForm()">+ เพิ่มรอบบำรุงรักษา</button><span class="badge danger">เกินกำหนด ${overdue}</span></div><div class="card"><p>ระบบคำนวณสถานะจากวันกำหนด: <b>ปกติ / ใกล้ครบกำหนด / เกินกำหนด / เสร็จแล้ว</b> และสามารถบันทึกหมายเหตุ/วันที่บำรุงรักษาล่าสุด</p>${maintTable(true)}</div>`}
function maintenanceStatus(m){if(m.status==='เสร็จแล้ว')return 'เสร็จแล้ว';if(m.due&&m.due<today())return 'เกินกำหนด';let d=(new Date(m.due)-new Date(today()))/86400000;if(d<=30)return 'ใกล้ครบกำหนด';return 'ปกติ'}
function maintTable(actions=false){return `<table><tr><th>เครื่องมือ</th><th>รอบ</th><th>กำหนดครั้งถัดไป</th><th>ล่าสุด</th><th>สถานะ</th>${actions?'<th>จัดการ</th>':''}</tr>${db.maintenance.map(m=>{let st=maintenanceStatus(m);return `<tr><td>${esc(name(m.asset))}<br><small>${esc(m.asset)}</small></td><td>${esc(m.cycle)}</td><td>${esc(m.due)}</td><td>${esc(m.lastDate||'-')}</td><td><span class="badge ${st==='ปกติ'||st==='เสร็จแล้ว'?'ok':st==='ใกล้ครบกำหนด'?'repair':'danger'}">${st}</span></td>${actions?`<td><button class="btn gray" onclick="maintForm(${m.id})">แก้ไข</button> <button class="btn red" onclick="deleteMaint(${m.id})">ลบ</button></td>`:''}</tr>`}).join('')||'<tr><td colspan="6" class="empty">ยังไม่มีข้อมูลรอบบำรุงรักษา</td></tr>'}</table>`}
function usage(){return `<div class="toolbar"><button class="btn orange" onclick="exportCSV('usage')">ส่งออกประวัติ CSV</button></div><div class="card"><h3>ประวัติการใช้งาน / ตรวจพบ RFID</h3>${db.usage.length?'<table><tr><th>เวลา</th><th>ผู้ใช้</th><th>ครุภัณฑ์</th><th>กิจกรรม</th></tr>'+db.usage.slice(0,500).map(x=>`<tr><td>${esc(x.time)}</td><td>${esc(x.user)}</td><td>${esc(name(x.asset))}</td><td>${esc(x.action)}</td></tr>`).join('')+'</table>':'<div class="empty">ยังไม่มีประวัติ</div>'}</div>`}
function repairs(){return `<div class="toolbar"><button class="btn" onclick="repairForm()">+ แจ้งซ่อม / เปิดใบงาน</button><button class="btn orange" onclick="exportCSV('repairs')">ส่งออก CSV</button></div><div class="card"><h3>การแจ้งซ่อมและซ่อมบำรุง</h3><table><tr><th>วันที่แจ้ง</th><th>ครุภัณฑ์</th><th>อาการ/ปัญหา</th><th>ผู้แจ้ง</th><th>สถานะ</th><th>จัดการ</th></tr>${db.repairs.map(r=>`<tr><td>${esc(r.reportDate)}</td><td>${esc(name(r.asset))}</td><td>${esc(r.problem)}</td><td>${esc(r.reporter)}</td><td><span class="badge ${r.status==='ซ่อมเสร็จ'?'ok':r.status==='กำลังซ่อม'?'repair':'danger'}">${esc(r.status)}</span></td><td><button class="btn gray" onclick="repairForm(${r.id})">แก้ไข</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">ยังไม่มีรายการซ่อม</td></tr>'}</table></div>`}
function reports(){return `<div class="grid"><div class="card"><h3>นำเข้าข้อมูล CSV</h3><p>เลือกประเภทข้อมูล แล้วเลือกไฟล์ CSV จากเครื่อง คอลัมน์ต้องตรงกับแม่แบบ</p><select id="csvType" onchange="csvTarget=this.value" style="width:100%;padding:10px;margin:8px 0"><option value="assets">ครุภัณฑ์</option><option value="users">ผู้ใช้งาน</option><option value="maintenance">Maintenance</option><option value="repairs">การซ่อม</option><option value="usage">ประวัติการใช้งาน</option></select><input type="file" id="csvFile" accept=".csv,text/csv" onchange="importCSV(event)" style="width:100%;padding:8px"><div class="notice">รองรับ UTF-8 และไฟล์จาก Excel ที่มี BOM. การนำเข้าจะ <b>เพิ่ม/อัปเดตรายการด้วย ID</b> โดยไม่ลบข้อมูลเดิม</div></div><div class="card"><h3>ส่งออกข้อมูล CSV</h3><p>ส่งออกฐานข้อมูลปัจจุบันไปเปิดต่อใน Excel ได้</p><div class="toolbar">${['assets','users','maintenance','repairs','usage'].map(x=>`<button class="btn" onclick="exportCSV('${x}')">${labelCSV(x)}</button>`).join('')}</div><h3>แม่แบบ CSV</h3><div class="toolbar">${['assets','users','maintenance','repairs','usage'].map(x=>`<button class="btn gray" onclick="downloadTemplate('${x}')">${labelCSV(x)}</button>`).join('')}</div></div></div>`}
function labelCSV(t){return {assets:'ครุภัณฑ์',users:'ผู้ใช้งาน',maintenance:'Maintenance',repairs:'การซ่อม',usage:'ประวัติการใช้งาน'}[t]}
const fields={assets:['id','name','brand','epc','status','room','user','image'],users:['id','name','username','password','role','active'],maintenance:['id','asset','due','cycle','status','lastDate','note'],repairs:['id','asset','reportDate','reporter','problem','status','startDate','finishDate','technician','cost','note'],usage:['id','time','user','asset','action']};
function csvCell(x){let s=String(x??'');return /[",\n\r]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
function exportCSV(type){let rows=db[type]||[], cols=fields[type];let text='\uFEFF'+cols.join(',')+'\n'+rows.map(r=>cols.map(c=>csvCell(r[c])).join(',')).join('\n');let blob=new Blob([text],{type:'text/csv;charset=utf-8;'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`sut-rfid-${type}-${today()}.csv`;a.click();URL.revokeObjectURL(a.href)}
function parseCSV(text){text=text.replace(/^\uFEFF/,'');let rows=[],row=[],cell='',q=false;for(let i=0;i<text.length;i++){let ch=text[i],n=text[i+1];if(ch==='"'){if(q&&n==='"'){cell+='"';i++}else q=!q}else if(ch===','&&!q){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!q){if(ch==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>x!==''))rows.push(row);row=[];cell=''}else cell+=ch}if(cell!==''||row.length){row.push(cell);rows.push(row)}return rows}
function importCSV(e){let file=e.target.files?.[0];if(!file)return;let type=document.getElementById('csvType')?.value||csvTarget;let reader=new FileReader();reader.onload=()=>{try{let rows=parseCSV(reader.result);if(rows.length<2)throw Error('ไฟล์ไม่มีข้อมูล');let headers=rows[0].map(x=>x.trim());let cols=fields[type];let missing=cols.filter(c=>!headers.includes(c));if(missing.length)throw Error('ขาดคอลัมน์: '+missing.join(', '));let added=0,updated=0;rows.slice(1).forEach(vals=>{let obj={};headers.forEach((h,i)=>obj[h]=vals[i]??'');if(type==='assets')obj.image=obj.image||'';if(type==='users')obj.active=String(obj.active).toLowerCase()!=='false';if(type==='maintenance'||type==='repairs'||type==='usage')obj.id=Number(obj.id)||uid();let arr=db[type],idx=arr.findIndex(x=>String(x.id)===String(obj.id));if(idx>=0){arr[idx]={...arr[idx],...obj};updated++}else{arr.push(obj);added++}});save();alert(`นำเข้าสำเร็จ\nเพิ่ม ${added} รายการ\nอัปเดต ${updated} รายการ`);e.target.value='';render()}catch(err){alert('นำเข้าไม่สำเร็จ: '+err.message)}};reader.readAsText(file,'utf-8')}
function downloadTemplate(type){let cols=fields[type];let sample={assets:['7440-001-0004/2563','เครื่องมือใหม่','ยี่ห้อ','300BB3A4F2C1E8D3','ใช้งานปกติ','ห้องปฏิบัติการ','',''],users:['10','ผู้ใช้งานใหม่','newuser','1234','user','true'],maintenance:['10','7440-001-0004/2563','2026-12-31','180 วัน','ปกติ','2026-06-30','ตรวจเช็ก'],repairs:['10','7440-001-0004/2563','2026-10-05','ผู้แจ้ง','เปิดไม่ติด','แจ้งซ่อม','','','','',''],usage:['10','2026-10-05 10:00:00','ผู้ใช้','7440-001-0004/2563','ใช้งาน']};let text='\uFEFF'+cols.join(',')+'\n'+sample[type].map(csvCell).join(',');let blob=new Blob([text],{type:'text/csv;charset=utf-8;'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`template-${type}.csv`;a.click();URL.revokeObjectURL(a.href)}
function assetForm(id){let a=db.assets.find(x=>x.id===id)||{id:'',name:'',brand:'',epc:'',status:'ใช้งานปกติ',room:'',user:'',image:''};showModal(`<h3>${id?'แก้ไข':'เพิ่ม'}ครุภัณฑ์</h3><div class="field"><label>เลขครุภัณฑ์ / ID</label><input id="f_id" value="${esc(a.id)}"></div><div class="field"><label>ชื่อครุภัณฑ์</label><input id="f_name" value="${esc(a.name)}"></div><div class="field"><label>ยี่ห้อ/รุ่น</label><input id="f_brand" value="${esc(a.brand)}"></div><div class="field"><label>EPC Tag</label><input id="f_epc" value="${esc(a.epc)}"></div><div class="field"><label>สถานะ</label><select id="f_status"><option>ใช้งานปกติ</option><option>กำลังใช้งาน</option><option>ส่งซ่อม</option><option>ถึงรอบบำรุงรักษา</option><option>ชำรุดรอจำหน่าย</option><option>ไม่พบจากการตรวจนับ</option></select></div><div class="field"><label>ห้อง/สถานที่</label><input id="f_room" value="${esc(a.room)}"></div><div class="field"><label>ผู้รับผิดชอบ/ผู้ใช้</label><input id="f_user" value="${esc(a.user)}"></div><div class="field"><label>รูปเครื่องมือ</label><input id="f_image" type="file" accept="image/*"></div>${a.image?`<img src="${a.image}" style="max-width:160px;border-radius:10px">`:''}<div class="toolbar"><button class="btn" onclick="saveAsset('${esc(id||'')}')">บันทึก</button><button class="btn gray" onclick="closeModal()">ยกเลิก</button>${id?`<button class="btn red" onclick="deleteAsset('${esc(id)}')">ลบ</button>`:''}</div>`);document.getElementById('f_status').value=a.status}
function saveAsset(oldId){let obj={id:v('f_id').trim(),name:v('f_name').trim(),brand:v('f_brand').trim(),epc:v('f_epc').trim(),status:v('f_status'),room:v('f_room').trim(),user:v('f_user').trim(),image:db.assets.find(x=>x.id===oldId)?.image||''};if(!obj.id||!obj.name)return alert('กรุณากรอกเลขครุภัณฑ์และชื่อครุภัณฑ์');let file=document.getElementById('f_image')?.files?.[0];let done=()=>{let idx=db.assets.findIndex(x=>x.id===oldId);if(idx>=0)db.assets[idx]=obj;else db.assets.push(obj);save();closeModal();render()};if(file){let r=new FileReader();r.onload=()=>{obj.image=r.result;done()};r.readAsDataURL(file)}else done()}
function deleteAsset(id){if(!confirm('ลบครุภัณฑ์นี้หรือไม่?'))return;db.assets=db.assets.filter(x=>x.id!==id);save();closeModal();render()}
function maintForm(id){let m=db.maintenance.find(x=>x.id===id)||{id:'',asset:db.assets[0]?.id||'',due:today(),cycle:'180 วัน',status:'ปกติ',lastDate:'',note:''};showModal(`<h3>${id?'แก้ไข':'เพิ่ม'}รอบบำรุงรักษา</h3><div class="field"><label>ครุภัณฑ์</label><select id="m_asset">${db.assets.map(a=>`<option value="${esc(a.id)}">${esc(a.name)} — ${esc(a.id)}</option>`).join('')}</select></div><div class="field"><label>กำหนดครั้งถัดไป</label><input id="m_due" type="date" value="${esc(m.due)}"></div><div class="field"><label>รอบการบำรุงรักษา</label><input id="m_cycle" value="${esc(m.cycle)}" placeholder="เช่น 180 วัน / 6 เดือน"></div><div class="field"><label>วันที่บำรุงรักษาล่าสุด</label><input id="m_last" type="date" value="${esc(m.lastDate||'')}"></div><div class="field"><label>หมายเหตุ</label><textarea id="m_note">${esc(m.note)}</textarea></div><div class="toolbar"><button class="btn" onclick="saveMaint(${id||0})">บันทึก</button><button class="btn gray" onclick="closeModal()">ยกเลิก</button></div>`);document.getElementById('m_asset').value=m.asset}
function saveMaint(id){let m={id:id||uid(),asset:v('m_asset'),due:v('m_due'),cycle:v('m_cycle'),status:'ปกติ',lastDate:v('m_last'),note:v('m_note')};let idx=db.maintenance.findIndex(x=>x.id==id);if(idx>=0)db.maintenance[idx]=m;else db.maintenance.push(m);save();closeModal();render()}
function deleteMaint(id){if(!confirm('ลบรอบบำรุงรักษานี้หรือไม่?'))return;db.maintenance=db.maintenance.filter(x=>x.id!==id);save();render()}
function repairForm(id){let r=db.repairs.find(x=>x.id===id)||{id:'',asset:db.assets[0]?.id||'',reportDate:today(),reporter:me.name,problem:'',status:'แจ้งซ่อม',startDate:'',finishDate:'',technician:'',cost:'',note:''};showModal(`<h3>${id?'แก้ไข':'เปิด'}ใบงานซ่อม</h3><div class="field"><label>ครุภัณฑ์</label><select id="r_asset">${db.assets.map(a=>`<option value="${esc(a.id)}">${esc(a.name)} — ${esc(a.id)}</option>`).join('')}</select></div><div class="field"><label>วันที่แจ้ง</label><input id="r_date" type="date" value="${esc(r.reportDate)}"></div><div class="field"><label>ผู้แจ้ง</label><input id="r_reporter" value="${esc(r.reporter)}"></div><div class="field"><label>อาการ/ปัญหา</label><textarea id="r_problem">${esc(r.problem)}</textarea></div><div class="field"><label>สถานะ</label><select id="r_status"><option>แจ้งซ่อม</option><option>รับงานแล้ว</option><option>กำลังซ่อม</option><option>รออะไหล่</option><option>ซ่อมเสร็จ</option><option>ยกเลิก</option></select></div><div class="field"><label>วันที่เริ่มซ่อม</label><input id="r_start" type="date" value="${esc(r.startDate)}"></div><div class="field"><label>วันที่ซ่อมเสร็จ</label><input id="r_finish" type="date" value="${esc(r.finishDate)}"></div><div class="field"><label>ช่าง/ผู้ดำเนินการ</label><input id="r_tech" value="${esc(r.technician)}"></div><div class="field"><label>ค่าใช้จ่าย</label><input id="r_cost" type="number" value="${esc(r.cost)}"></div><div class="field"><label>หมายเหตุ</label><textarea id="r_note">${esc(r.note)}</textarea></div><div class="toolbar"><button class="btn" onclick="saveRepair(${id||0})">บันทึก</button><button class="btn gray" onclick="closeModal()">ยกเลิก</button></div>`);document.getElementById('r_asset').value=r.asset;document.getElementById('r_status').value=r.status}
function saveRepair(id){let r={id:id||uid(),asset:v('r_asset'),reportDate:v('r_date'),reporter:v('r_reporter'),problem:v('r_problem'),status:v('r_status'),startDate:v('r_start'),finishDate:v('r_finish'),technician:v('r_tech'),cost:v('r_cost'),note:v('r_note')};let idx=db.repairs.findIndex(x=>x.id==id);if(idx>=0)db.repairs[idx]=r;else db.repairs.unshift(r);let a=db.assets.find(x=>x.id===r.asset);if(a)a.status=r.status==='ซ่อมเสร็จ'?'ใช้งานปกติ':'ส่งซ่อม';save();closeModal();render()}
function users(){return `<div class="toolbar"><button class="btn" onclick="userForm()">+ เพิ่มผู้ใช้งาน</button><button class="btn orange" onclick="go('reports')">นำเข้า/ส่งออก CSV</button></div><div class="card"><table><tr><th>ชื่อ</th><th>Username</th><th>สิทธิ์</th><th>สถานะ</th><th>จัดการ</th></tr>${db.users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.username)}</td><td>${esc(u.role)}</td><td><span class="badge ${u.active?'ok':'danger'}">${u.active?'ใช้งาน':'ปิดใช้งาน'}</span></td><td><button class="btn gray" onclick="userForm(${u.id})">แก้ไข</button></td></tr>`).join('')}</table></div>`}
function userForm(id){let u=db.users.find(x=>x.id===id)||{id:'',name:'',username:'',password:'',role:'user',active:true};showModal(`<h3>${id?'แก้ไข':'เพิ่ม'}ผู้ใช้งาน</h3><div class="field"><label>ชื่อ</label><input id="u_name" value="${esc(u.name)}"></div><div class="field"><label>Username</label><input id="u_username" value="${esc(u.username)}"></div><div class="field"><label>Password</label><input id="u_password" type="password" value="${esc(u.password)}"></div><div class="field"><label>สิทธิ์</label><select id="u_role"><option value="user">user</option><option value="admin">admin</option></select></div><div class="field"><label><input id="u_active" type="checkbox" ${u.active?'checked':''}> เปิดใช้งาน</label></div><div class="toolbar"><button class="btn" onclick="saveUser(${id||0})">บันทึก</button><button class="btn gray" onclick="closeModal()">ยกเลิก</button></div>`);document.getElementById('u_role').value=u.role}
function saveUser(id){let u={id:id||uid(),name:v('u_name').trim(),username:v('u_username').trim(),password:v('u_password'),role:v('u_role'),active:document.getElementById('u_active').checked};if(!u.name||!u.username||!u.password)return alert('กรุณากรอกข้อมูลผู้ใช้ให้ครบ');if(db.users.some(x=>x.username===u.username&&x.id!==u.id))return alert('Username นี้มีอยู่แล้ว');let idx=db.users.findIndex(x=>x.id==id);if(idx>=0)db.users[idx]=u;else db.users.push(u);if(me.id===u.id){me=u;localStorage.setItem('sut_user',u.username)}save();closeModal();render()}
function settings(){return `<div class="card"><h3>ตั้งค่าบัญชีของฉัน</h3><p>เปลี่ยนรหัสผ่านสำหรับผู้ใช้ที่กำลังเข้าสู่ระบบ</p><button class="btn" onclick="passwordForm()">เปลี่ยนรหัสผ่าน</button><h3 style="margin-top:25px">ข้อมูลระบบ</h3><p>ฐานข้อมูลทำงานบน LocalStorage ของเบราว์เซอร์นี้ และไฟล์ CSV ใช้สำรอง/ย้ายข้อมูล</p><p class="notice">หมายเหตุ: GitHub Pages เป็นเว็บแบบ static จึงไม่มีฐานข้อมูลกลาง หากต้องการให้หลายเครื่องเห็นข้อมูลชุดเดียวกัน ต้องเชื่อม backend เช่น Supabase/Firebase ในขั้นถัดไป</p></div>`}
function passwordForm(){showModal(`<h3>เปลี่ยนรหัสผ่าน</h3><div class="field"><label>รหัสผ่านเดิม</label><input id="p_old" type="password"></div><div class="field"><label>รหัสผ่านใหม่</label><input id="p_new" type="password"></div><div class="field"><label>ยืนยันรหัสผ่านใหม่</label><input id="p_confirm" type="password"></div><button class="btn" onclick="savePassword()">บันทึก</button> <button class="btn gray" onclick="closeModal()">ยกเลิก</button>`)}
function savePassword(){if(v('p_old')!==me.password)return alert('รหัสผ่านเดิมไม่ถูกต้อง');if(!v('p_new')||v('p_new')!==v('p_confirm'))return alert('รหัสผ่านใหม่ไม่ตรงกัน');me.password=v('p_new');let u=db.users.find(x=>x.id===me.id);if(u)u.password=me.password;save();closeModal();alert('เปลี่ยนรหัสผ่านแล้ว')}
function showModal(html){let m=document.getElementById('modal');m.innerHTML=`<div class="box">${html}</div>`;m.classList.add('show')}
function closeModal(){let m=document.getElementById('modal');if(m){m.classList.remove('show');m.innerHTML=''}}
window.login=login;window.logout=logout;window.go=go;window.connectESP32=connectESP32;window.startDemoScan=startDemoScan;window.stopScan=stopScan;window.clearScan=clearScan;window.assetForm=assetForm;window.saveAsset=saveAsset;window.deleteAsset=deleteAsset;window.maintForm=maintForm;window.saveMaint=saveMaint;window.deleteMaint=deleteMaint;window.repairForm=repairForm;window.saveRepair=saveRepair;window.userForm=userForm;window.saveUser=saveUser;window.passwordForm=passwordForm;window.savePassword=savePassword;window.closeModal=closeModal;window.exportCSV=exportCSV;window.downloadTemplate=downloadTemplate;window.importCSV=importCSV;window.filterAssets=filterAssets;
save();render();
