const K='sut_rfid_db_v4';
const seed={users:[{id:1,name:'ผู้ดูแลระบบ',username:'admin',password:'admin123',role:'admin',active:true},{id:2,name:'ดิเรกฤทธิ์ แสงโชติ',username:'direkrit',password:'1234',role:'user',active:true}],assets:[{id:'7440-001-0001/2563',name:'เครื่องคอมพิวเตอร์',brand:'Acer Aspire 5',epc:'300BB3A4F2C1E8D0',status:'ใช้งานปกติ',room:'ห้องปฏิบัติการคอมพิวเตอร์',user:'ดิเรกฤทธิ์ แสงโชติ',image:''},{id:'7440-001-0002/2563',name:'เครื่องปั่นเหวี่ยง',brand:'Eppendorf',epc:'300BB3A4F2C1E8D1',status:'ส่งซ่อม',room:'ห้องปฏิบัติการ',user:'',image:''},{id:'7440-001-0003/2563',name:'ตู้เย็นเก็บตัวอย่าง',brand:'Sanyo',epc:'300BB3A4F2C1E8D2',status:'ถึงรอบบำรุงรักษา',room:'ห้องเก็บตัวอย่าง',user:'',image:''}],maintenance:[{id:1,asset:'7440-001-0002/2563',due:'2026-10-12',cycle:'180 วัน',status:'ใกล้ครบกำหนด',note:''}],repairs:[],usage:[]};
let db=JSON.parse(localStorage.getItem(K)||'null')||JSON.parse(localStorage.getItem('sut_rfid_db_v3')||'null')||seed;
db.users??=[];db.assets??=[];db.maintenance??=[];db.repairs??=[];db.usage??=[];db.assets.forEach(a=>a.image??='');
let me=null,page='home',serialPort=null,serialReader=null,scanRunning=false,scanSeen=new Set();
try{me=db.users.find(u=>u.username===localStorage.getItem('sut_user')&&u.active)||null}catch(e){}
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const save=()=>localStorage.setItem(K,JSON.stringify(db));
const go=p=>{page=p;render()};
const v=id=>document.getElementById(id)?.value||'';
const today=()=>new Date().toISOString().slice(0,10);
function login(){const u=db.users.find(x=>x.username===v('lu')&&x.password===v('lp')&&x.active);if(!u)return alert('ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง');me=u;localStorage.setItem('sut_user',u.username);render()}
function logout(){me=null;localStorage.removeItem('sut_user');render()}
function render(){document.getElementById('app').innerHTML=me?shell():loginPage()}
function loginPage(){return `<div class="login"><div class="loginbox"><img src="sut-logo.jpg"><h2>ระบบจัดการครุภัณฑ์ RFID</h2><div class="orange">ศูนย์เครื่องมือวิทยาศาสตร์และเทคโนโลยี</div><div class="field"><label>ชื่อผู้ใช้งาน</label><input id="lu" autocomplete="username"></div><div class="field"><label>รหัสผ่าน</label><input id="lp" type="password" autocomplete="current-password"></div><button class="btn" onclick="login()">เข้าสู่ระบบ</button><p style="font-size:12px;color:#8998a8">เริ่มต้น: admin / admin123</p></div></div>`}
function shell(){let nav=[['home','หน้าหลัก'],['scan','ตรวจนับ RFID'],['assets','จัดการครุภัณฑ์'],['maintenance','Maintenance'],['usage','ประวัติการใช้งาน'],['repairs','ประวัติการซ่อม'],['reports','นำเข้า / ส่งออก']];if(me.role==='admin')nav.push(['users','จัดการผู้ใช้งาน']);nav.push(['settings','ตั้งค่า']);return `<div class="layout"><aside class="side"><div class="brand"><img src="sut-logo.jpg"><div><b>ศูนย์เครื่องมือวิทยาศาสตร์และเทคโนโลยี</b><small>มหาวิทยาลัยเทคโนโลยีสุรนารี</small></div></div><div class="nav">${nav.map(n=>`<button class="${page===n[0]?'active':''}" onclick="go('${n[0]}')">${n[1]}</button>`).join('')}</div></aside><main class="main"><header class="top"><b>${title()}</b><div>👤 ${esc(me.name)} &nbsp; <button class="btn gray" onclick="logout()">ออกจากระบบ</button></div></header><section class="content">${body()}</section></main></div><div id="modal" class="modal"></div>`}
function title(){return {home:'หน้าหลัก',scan:'ตรวจนับ RFID',assets:'จัดการครุภัณฑ์',maintenance:'Maintenance / รอบบำรุงรักษา',usage:'ประวัติการใช้งาน',repairs:'ประวัติการซ่อม',reports:'นำเข้า / ส่งออกข้อมูล',users:'จัดการผู้ใช้งาน',settings:'ตั้งค่า'}[page]||'หน้าหลัก'}
function counts(){let a=db.assets;return [a.length,a.filter(x=>x.status==='ใช้งานปกติ').length,a.filter(x=>x.status==='ส่งซ่อม').length,a.filter(x=>x.status==='ถึงรอบบำรุงรักษา').length,db.users.filter(x=>x.active).length]}
function body(){if(page==='home')return home();if(page==='scan')return scan();if(page==='assets')return assets();if(page==='maintenance')return maintenance();if(page==='usage')return usage();if(page==='repairs')return repairs();if(page==='reports')return reports();if(page==='users'&&me.role==='admin')return users();return settings()}
function home(){let[t,o,r,d,u]=counts();return `<div class="hero"><div class="heroLeft"><img src="sut-logo.jpg"><div><h1>ศูนย์เครื่องมือวิทยาศาสตร์และเทคโนโลยี</h1><div class="orange">มหาวิทยาลัยเทคโนโลยีสุรนารี</div></div></div><div><h2>ระบบบริหารจัดการครุภัณฑ์ RFID</h2><div style="color:#718096">ตรวจนับ • ติดตาม • บำรุงรักษา • นำเข้า/ส่งออกข้อมูล</div></div></div><div class="cards"><div class="stat s1">ครุภัณฑ์ทั้งหมด<b>${t}</b>รายการ</div><div class="stat s2">ใช้งานปกติ<b>${o}</b>รายการ</div><div class="stat s3">ส่งซ่อม<b>${r}</b>รายการ</div><div class="stat s4">ถึงรอบบำรุงรักษา<b>${d}</b>รายการ</div><div class="stat s5">ผู้ใช้งาน<b>${u}</b>คน</div></div><div class="grid"><div class="card"><h3>สถานะครุภัณฑ์</h3>${['ใช้งานปกติ','ส่งซ่อม','ถึงรอบบำรุงรักษา'].map((s,i)=>{let n=[o,r,d][i],p=t?Math.round(n/t*100):0;return `<p>${s}<b style="float:right">${n} (${p}%)</b></p><div style="height:9px;background:#edf1f5;border-radius:9px"><div style="width:${p}%;height:100%;background:${['#13a66a','#f28c18','#e94b4b'][i]};border-radius:9px"></div></div>`}).join('')}</div><div class="card"><h3>รายการแจ้งเตือน</h3>${db.maintenance.slice(0,8).map(m=>`<p>🔧 ${esc(name(m.asset))}<span class="badge repair" style="float:right">${esc(m.status)}</span></p>`).join('')||'<div class="empty">ไม่มีรายการ</div>'}</div></div><div class="grid"><div class="card"><h3>ครุภัณฑ์ล่าสุด</h3>${tableAssets(db.assets.slice(-5).reverse())}</div><div class="card"><h3>บำรุงรักษารอบถัดไป</h3>${maintTable()}</div></div>`}
function name(id){return db.assets.find(a=>a.id===id)?.name||id}
function cls(s){return s==='ใช้งานปกติ'?'ok':s==='ส่งซ่อม'?'repair':'danger'}
function tableAssets(a){return `<table><tr><th>ครุภัณฑ์</th><th>EPC</th><th>สถานะ</th><th></th></tr>${a.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.epc)}</td><td><span class="badge ${cls(x.status)}">${esc(x.status)}</span></td><td><button class="btn gray" onclick="assetForm('${esc(x.id)}')">ดู/แก้ไข</button></td></tr>`).join('')}</table>`}
function assets(){return `<div class="toolbar"><button class="btn" onclick="assetForm()">+ เพิ่มครุภัณฑ์</button><button class="btn orange" onclick="go('reports')">นำเข้า/ส่งออก CSV</button></div><div class="card">${tableAssets(db.assets)}</div>`}
function scan(){let found=[...scanSeen].map(epc=>db.assets.find(a=>a.epc===epc)).filter(Boolean);return `<div class="grid"><div class="card"><h3>ตรวจนับ RFID / ESP32</h3><p>รองรับ Web Serial ใน Chrome/Edge บนคอมพิวเตอร์ที่ต่อ ESP32 ผ่าน USB. ส่ง EPC ทีละบรรทัด เช่น <b>300BB3A4F2C1E8D0</b></p><div class="toolbar"><button class="btn" onclick="connectESP32()">🔌 เชื่อมต่อ ESP32</button><button class="btn orange" onclick="startDemoScan()">เริ่มสแกนจำลอง</button><button class="btn gray" onclick="stopScan()">หยุด</button></div><div id="serialStatus" class="notice">${scanRunning?'กำลังรับข้อมูลจาก ESP32':'ยังไม่ได้เชื่อมต่อ'}</div><p>พบแล้ว <b>${found.length}</b> / ${db.assets.length} รายการ</p></div><div class="card"><h3>ผลการตรวจนับ</h3>${found.length?tableAssets(found):'<div class="empty">ยังไม่พบ EPC ที่ตรงกับฐานข้อมูล</div>'}</div></div>`}
async function connectESP32(){if(!('serial' in navigator))return alert('เบราว์เซอร์นี้ไม่รองรับ Web Serial กรุณาใช้ Chrome/Edge และเชื่อม ESP32 ผ่าน USB');try{serialPort=await navigator.serial.requestPort();await serialPort.open({baudRate:115200});scanRunning=true;scanSeen=new Set();render();const decoder=new TextDecoderStream();serialPort.readable.pipeTo(decoder.writable);serialReader=decoder.readable.getReader();readSerial()}catch(e){alert('เชื่อมต่อ ESP32 ไม่สำเร็จ: '+e.message)}}
async function readSerial(){while(scanRunning&&serialReader){try{const {value,done}=await serialReader.read();if(done)break;if(value){value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).forEach(recordEPC)}}catch(e){break}}}
function recordEPC(epc){epc=String(epc).trim();if(!epc)return;scanSeen.add(epc.toUpperCase());let a=db.assets.find(x=>String(x.epc).toUpperCase()===epc.toUpperCase());if(a){db.usage.unshift({id:Date.now(),time:new Date().toLocaleString('th-TH'),user:me.name,asset:a.id,action:'ตรวจพบ RFID'});save()}if(page==='scan')render()}
async function stopScan(){scanRunning=false;try{if(serialReader){await serialReader.cancel();serialReader=null}if(serialPort){await serialPort.close();serialPort=null}}catch(e){}if(page==='scan')render()}
function startDemoScan(){scanRunning=true;scanSeen=new Set(db.assets.map(a=>a.epc).filter(Boolean));db.assets.forEach(a=>db.usage.unshift({id:Date.now()+Math.random(),time:new Date().toLocaleString('th-TH'),user:me.name,asset:a.id,action:'ตรวจพบ RFID (จำลอง)'}));save();render()}
function maintenance(){return `<div class="toolbar"><button class="btn" onclick="maintForm()">+ เพิ่มรอบบำรุงรักษา</button></div><div class="card">${maintTable(true)}</div>`}
function maintTable(actions=false){return `<table><tr><th>เครื่องมือ</th><th>รอบ</th><th>กำหนด</th><th>สถานะ</th>${actions?'<th>จัดการ</th>':''}</tr>${db.maintenance.map(m=>`<tr><td>${esc(name(m.asset))}</td><td>${esc(m.cycle)}</td><td>${esc(m.due)}</td><td><span class="badge ${m.status==='ปกติ'?'ok':'repair'}">${esc(m.status)}</span></td>${actions?`<td><button class="btn gray" onclick="maintForm(${m.id})">แก้ไข</button> <button class="btn dangerBtn" onclick="deleteMaint(${m.id})">ลบ</button></td>`:''}</tr>`).join('')}</table>`}
function usage(){return `<div class="card"><h3>ประวัติการใช้งาน / ตรวจพบ RFID</h3>${db.usage.length?'<table><tr><th>เวลา</th><th>ผู้ใช้</th><th>เครื่องมือ</th><th>กิจกรรม</th></tr>'+db.usage.map(x=>`<tr><td>${esc(x.time)}</td><td>${esc(x.user)}</td><td>${esc(name(x.asset))}</td><td>${esc(x.action||'ใช้งาน')}</td></tr>`).join('')+'</table>':'<div class="empty">ยังไม่มีประวัติ</div>'}</div>`}
function repairs(){return `<div class="toolbar"><button class="btn" onclick="repairForm()">+ แจ้งซ่อม</button></div><div class="card"><h3>ประวัติการซ่อม</h3>${db.repairs.length?'<table><tr><th>เครื่องมือ</th><th>วันที่</th><th>อาการ</th><th>สถานะ</th><th></th></tr>'+db.repairs.map(x=>`<tr><td>${esc(name(x.asset))}</td><td>${esc(x.date)}</td><td>${esc(x.problem)}</td><td>${esc(x.status||'แจ้งซ่อม')}</td><td><button class="btn gray" onclick="deleteRepair(${x.id})">ลบ</button></td></tr>`).join('')+'</table>':'<div class="empty">ยังไม่มีรายการซ่อม</div>'}</div>`}
function reports(){return `<div class="grid"><div class="card"><h3>นำเข้าครุภัณฑ์ CSV</h3><p>หัวตาราง: id,name,brand,epc,status,room,user,image</p><input id="csvAssets" type="file" accept=".csv"><br><br><button class="btn" onclick="importCSV('assets')">นำเข้าครุภัณฑ์</button></div><div class="card"><h3>นำเข้าผู้ใช้งาน CSV</h3><p>หัวตาราง: name,username,password,role,active</p><input id="csvUsers" type="file" accept=".csv"><br><br><button class="btn" onclick="importCSV('users')">นำเข้าผู้ใช้งาน</button></div><div class="card"><h3>ส่งออกข้อมูล</h3><button class="btn" onclick="expAssets()">ส่งออกครุภัณฑ์ CSV</button> <button class="btn gray" onclick="expUsers()">ส่งออกผู้ใช้ CSV</button> <button class="btn gray" onclick="expMaint()">ส่งออก Maintenance CSV</button> <button class="btn gray" onclick="backupJSON()">สำรองข้อมูล JSON</button></div></div>`}
function users(){return `<div class="toolbar"><button class="btn" onclick="userForm()">+ เพิ่มผู้ใช้</button><button class="btn orange" onclick="go('reports')">นำเข้า/ส่งออก CSV</button></div><div class="card"><table><tr><th>ชื่อ</th><th>Username</th><th>สิทธิ์</th><th>สถานะ</th><th>จัดการ</th></tr>${db.users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.username)}</td><td>${esc(u.role)}</td><td>${u.active?'ใช้งาน':'ปิดใช้งาน'}</td><td><button class="btn gray" onclick="userForm(${u.id})">แก้ไข</button> <button class="btn dangerBtn" onclick="deleteUser(${u.id})">ลบ</button></td></tr>`).join('')}</table></div>`}
function settings(){return `<div class="card"><h3>ตั้งค่าบัญชี</h3><p>บัญชีปัจจุบัน: <b>${esc(me.username)}</b></p><button class="btn" onclick="userForm(${me.id})">เปลี่ยนชื่อผู้ใช้ / Password</button><p style="color:#a86200">ข้อมูลเวอร์ชัน GitHub Pages นี้เก็บใน localStorage ของเบราว์เซอร์แต่ละเครื่อง</p></div>`}
function modal(h){document.getElementById('modal').innerHTML='<div class="box">'+h+'</div>';document.getElementById('modal').classList.add('show')}
function closeM(){document.getElementById('modal').classList.remove('show')}
function assetForm(id=''){let a=db.assets.find(x=>x.id===id)||{id:'',name:'',brand:'',epc:'',status:'ใช้งานปกติ',room:'',user:'',image:''};modal(`<h3>${id?'แก้ไข':'เพิ่ม'}ครุภัณฑ์</h3>${['id','name','brand','epc','room','user'].map(k=>`<div class="field"><label>${k}</label><input id="a_${k}" value="${esc(a[k])}"></div>`).join('')}<div class="field"><label>สถานะ</label><select id="a_status">${['ใช้งานปกติ','ส่งซ่อม','ถึงรอบบำรุงรักษา','ระงับการใช้งาน','เลิกใช้งาน'].map(s=>`<option ${a.status===s?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>รูปเครื่องมือ</label><input id="a_image_file" type="file" accept="image/*" onchange="previewAssetImage()"><input id="a_image" type="hidden" value="${esc(a.image||'')}">${a.image?`<img id="a_preview" src="${esc(a.image)}" style="max-width:160px;max-height:120px;display:block;margin-top:8px;border-radius:8px">`:'<img id="a_preview" style="max-width:160px;max-height:120px;display:none;margin-top:8px;border-radius:8px">'}</div><button class="btn" onclick="saveA('${esc(id)}')">บันทึก</button> <button class="btn gray" onclick="closeM()">ยกเลิก</button> ${id?`<button class="btn dangerBtn" onclick="deleteAsset('${esc(id)}')">ลบครุภัณฑ์</button>`:''}`)}
function previewAssetImage(){const f=document.getElementById('a_image_file').files[0];if(!f)return;const r=new FileReader();r.onload=()=>{document.getElementById('a_image').value=r.result;const p=document.getElementById('a_preview');p.src=r.result;p.style.display='block'};r.readAsDataURL(f)}
function saveA(old){let a={id:v('a_id'),name:v('a_name'),brand:v('a_brand'),epc:v('a_epc'),room:v('a_room'),user:v('a_user'),status:v('a_status'),image:v('a_image')};if(!a.id||!a.name)return alert('กรุณากรอกเลขครุภัณฑ์และชื่อครุภัณฑ์');let i=db.assets.findIndex(x=>x.id===old);if(i>=0)db.assets[i]=a;else db.assets.push(a);save();closeM();render()}
function deleteAsset(id){if(!confirm('ยืนยันลบครุภัณฑ์นี้?'))return;db.assets=db.assets.filter(x=>x.id!==id);db.maintenance=db.maintenance.filter(x=>x.asset!==id);save();closeM();render()}
function maintForm(id){let m=db.maintenance.find(x=>x.id==id)||{asset:db.assets[0]?.id||'',cycle:'180 วัน',due:'',status:'ปกติ',note:''};modal(`<h3>${id?'แก้ไข':'เพิ่ม'}รอบบำรุงรักษา</h3><div class="field"><label>ครุภัณฑ์</label><select id="m_a">${db.assets.map(a=>`<option value="${esc(a.id)}" ${a.id===m.asset?'selected':''}>${esc(a.name)}</option>`).join('')}</select></div><div class="field"><label>รอบ</label><input id="m_c" value="${esc(m.cycle)}"></div><div class="field"><label>กำหนด</label><input id="m_d" type="date" value="${esc(m.due)}"></div><div class="field"><label>สถานะ</label><select id="m_s"><option ${m.status==='ปกติ'?'selected':''}>ปกติ</option><option ${m.status==='ใกล้ครบกำหนด'?'selected':''}>ใกล้ครบกำหนด</option><option ${m.status==='เกินกำหนด'?'selected':''}>เกินกำหนด</option><option ${m.status==='ดำเนินการแล้ว'?'selected':''}>ดำเนินการแล้ว</option></select></div><div class="field"><label>หมายเหตุ</label><input id="m_n" value="${esc(m.note||'')}"></div><button class="btn" onclick="saveM(${id||0})">บันทึก</button> <button class="btn gray" onclick="closeM()">ยกเลิก</button>`)}
function saveM(id){let m={id:id||Date.now(),asset:v('m_a'),cycle:v('m_c'),due:v('m_d'),status:v('m_s'),note:v('m_n')};let i=db.maintenance.findIndex(x=>x.id==id);if(i>=0)db.maintenance[i]=m;else db.maintenance.push(m);save();closeM();render()}
function deleteMaint(id){if(!confirm('ลบรายการ Maintenance นี้?'))return;db.maintenance=db.maintenance.filter(x=>x.id!=id);save();render()}
function repairForm(){modal(`<h3>แจ้งซ่อม</h3><div class="field"><label>ครุภัณฑ์</label><select id="r_a">${db.assets.map(a=>`<option value="${esc(a.id)}">${esc(a.name)}</option>`).join('')}</select></div><div class="field"><label>วันที่</label><input id="r_d" type="date" value="${today()}"></div><div class="field"><label>อาการ/ปัญหา</label><textarea id="r_p" rows="4"></textarea></div><button class="btn" onclick="saveRepair()">บันทึกแจ้งซ่อม</button> <button class="btn gray" onclick="closeM()">ยกเลิก</button>`)}
function saveRepair(){let asset=v('r_a');db.repairs.unshift({id:Date.now(),asset,date:v('r_d'),problem:v('r_p'),status:'แจ้งซ่อม',user:me.name});let a=db.assets.find(x=>x.id===asset);if(a)a.status='ส่งซ่อม';save();closeM();render()}
function deleteRepair(id){if(!confirm('ลบประวัติการซ่อมนี้?'))return;db.repairs=db.repairs.filter(x=>x.id!=id);save();render()}
function userForm(id){let u=db.users.find(x=>x.id==id)||{name:'',username:'',password:'',role:'user',active:true};modal(`<h3>${id?'แก้ไข':'เพิ่ม'}ผู้ใช้งาน</h3><div class="field"><label>ชื่อ</label><input id="u_n" value="${esc(u.name)}"></div><div class="field"><label>Username</label><input id="u_u" value="${esc(u.username)}"></div><div class="field"><label>Password</label><input id="u_p" type="password" value="${esc(u.password)}"></div><div class="field"><label>สิทธิ์</label><select id="u_r"><option value="user" ${u.role==='user'?'selected':''}>user</option><option value="admin" ${u.role==='admin'?'selected':''}>admin</option></select></div><div class="field"><label><input id="u_a" type="checkbox" ${u.active?'checked':''}> เปิดใช้งาน</label></div><button class="btn" onclick="saveU(${id||0})">บันทึก</button> <button class="btn gray" onclick="closeM()">ยกเลิก</button>`)}
function saveU(id){if(me.role!=='admin'&&id!==me.id)return alert('เฉพาะ Admin เท่านั้นที่แก้ไขผู้ใช้อื่นได้');let u={id:id||Date.now(),name:v('u_n'),username:v('u_u'),password:v('u_p'),role:v('u_r'),active:document.getElementById('u_a').checked};if(!u.name||!u.username||!u.password)return alert('กรุณากรอกข้อมูลให้ครบ');if(db.users.some(x=>x.username===u.username&&x.id!==u.id))return alert('Username นี้มีอยู่แล้ว');if(id===me.id)u.role=me.role;let i=db.users.findIndex(x=>x.id==id);if(i>=0)db.users[i]=u;else db.users.push(u);save();me=db.users.find(x=>x.id===me.id);localStorage.setItem('sut_user',me.username);closeM();render()}
function deleteUser(id){if(me.role!=='admin')return alert('เฉพาะ Admin เท่านั้น');if(id===me.id)return alert('ไม่สามารถลบบัญชีที่กำลังใช้งานอยู่');let u=db.users.find(x=>x.id==id);if(!u)return;if(!confirm(`ยืนยันลบผู้ใช้ ${u.username}?`))return;db.users=db.users.filter(x=>x.id!=id);save();render()}
function parseCSV(text){let rows=[],row=[],cell='',q=false;for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()!==''))rows.push(row);row=[];cell=''}else cell+=c}if(cell!==''||row.length){row.push(cell);rows.push(row)}return rows}
function importCSV(type){let input=document.getElementById(type==='assets'?'csvAssets':'csvUsers');let f=input?.files[0];if(!f)return alert('เลือกไฟล์ CSV ก่อน');let r=new FileReader();r.onload=()=>{let rows=parseCSV(r.result.replace(/^\uFEFF/,''));if(!rows.length)return alert('CSV ว่าง');let h=rows.shift().map(x=>x.trim().toLowerCase());let get=(row,key)=>row[h.indexOf(key)]??'';if(type==='assets'){rows.forEach(row=>{let a={id:get(row,'id'),name:get(row,'name'),brand:get(row,'brand'),epc:get(row,'epc'),status:get(row,'status')||'ใช้งานปกติ',room:get(row,'room'),user:get(row,'user'),image:get(row,'image')};if(!a.id)return;let i=db.assets.findIndex(x=>x.id===a.id);if(i>=0)db.assets[i]=a;else db.assets.push(a)})}else{if(me.role!=='admin')return alert('เฉพาะ Admin เท่านั้นที่นำเข้าผู้ใช้งาน');rows.forEach(row=>{let u={id:Date.now()+Math.random(),name:get(row,'name'),username:get(row,'username'),password:get(row,'password'),role:get(row,'role')||'user',active:String(get(row,'active')).toLowerCase()!=='false'};if(!u.username||!u.password)return;let i=db.users.findIndex(x=>x.username===u.username);if(i>=0)db.users[i]=u;else db.users.push(u)})}save();render();alert('นำเข้า CSV สำเร็จ')} ;r.readAsText(f,'UTF-8')}
function download(rows,file){if(!rows.length)return alert('ไม่มีข้อมูล');let keys=Object.keys(rows[0]);let csv='\uFEFF'+keys.join(',')+'\n'+rows.map(r=>keys.map(k=>'"'+String(r[k]??'').replaceAll('"','""')+'"').join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=file;a.click();URL.revokeObjectURL(a.href)}
function expAssets(){download(db.assets,'sut-assets.csv')}function expUsers(){download(db.users.map(u=>({name:u.name,username:u.username,password:u.password,role:u.role,active:u.active})),'sut-users.csv')}function expMaint(){download(db.maintenance,'sut-maintenance.csv')}function backupJSON(){download([{backup:JSON.stringify(db)}],'sut-rfid-backup.csv')}
Object.assign(window,{login,logout,go,assetForm,closeM,saveA,deleteAsset,maintForm,saveM,deleteMaint,repairForm,saveRepair,deleteRepair,userForm,saveU,deleteUser,importCSV,expAssets,expUsers,expMaint,backupJSON,connectESP32,startDemoScan,stopScan,previewAssetImage});
render();